version: '3'

tasks:
  env:
    desc: Set up the environment
    cmds:
      - cp .env.example .env

  install:
    desc: Install project dependencies
    cmds:
      - uv sync --all-groups

  format:
    desc: Format Python files with isort and black
    cmds:
      - uv run isort src/
      - uv run black src/
    sources:
      - "src/*.py"

  run:
    desc: Run the meal planner script
    cmds:
      - uv run python src/meal_planner.py
